Repository bar-d/ios-diary, pull requests merged in 2022-08, with the labels that each got.

#1 Feat 1 diary collection view controller
  .swiftlint.yml
  Diary.xcodeproj/project.pbxproj
  Diary/Date+Extension.swift
  Diary/DiaryListCollectionViewCell.swift
  Diary/DiaryListViewController.swift
  Diary/JSONModel.swift
  Diary/Resources/Assets.xcassets/sample.dataset/Contents.json
  Diary/Resources/Assets.xcassets/sample.dataset/sample.json
  Diary/Section.swift
Labels: feat, refactor

#2 Feat 2 diary detail view controller
  Diary.xcodeproj/project.pbxproj
  Diary/Date+Extension.swift
  Diary/DiaryDetailViewController.swift
  Diary/DiaryListViewController.swift
  Diary/protocol/DataSendable.swift
Labels: feat, refactor

#3 Feat 3 diary registration view controller
  Diary.xcodeproj/project.pbxproj
  Diary/DiaryDetailViewController.swift
  Diary/Extension/Date+Extension.swift
  Diary/Extension/TimeInterval+Extension.swift
  Diary/JSONModel/JSONModel.swift
  Diary/Manager/KeyboardManager.swift
  Diary/Protocol/DataSendable.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryDetail/View/DiaryDetailTextView.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/Enum/Section.swift
  Diary/Scene/DiaryList/View/DiaryListCollectionViewCell.swift
  Diary/Scene/DiaryRegistration/Controller/DiaryRegistrationViewController.swift
  Diary/Scene/DiaryRegistration/View/DiaryRegistrationView.swift
Labels: feat, style

#4 Feat 3 diary registration
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
Labels: refactor, hotfix

#5 Refactor 1 step1
  Diary.xcodeproj/project.pbxproj
  Diary/Extension/Array+Extension.swift
  Diary/JSONModel/Diary.swift
  Diary/Manager/KeyboardManager.swift
  Diary/Protocol/ReuseIdentifiable.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/MockDiaryManager.swift
  Diary/Scene/DiaryList/View/DiaryListCollectionViewCell.swift
  Diary/Scene/DiaryRegistration/Controller/DiaryRegistrationViewController.swift
Labels: feat, refactor, style

#6 Feat 4 alert controller
  Diary.xcodeproj/project.pbxproj
  Diary/DiaryEntity+CoreDataClass.swift
  Diary/DiaryEntity+CoreDataProperties.swift
  Diary/Manager/CoreDataManager.swift
  Diary/Manager/MockDiaryManager.swift
  Diary/Protocol/DataManagable.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryList/Model/MockDiaryManager.swift
  Diary/Scene/DiaryRegistration/Controller/DiaryRegistrationViewController.swift
Labels: feat, style

#7 Refactor 2 step2
  Diary/Manager/DiaryCoreDataManager.swift
  Diary/Scene/DiaryDetail/Controller/DiaryDetailViewController.swift
  Diary/Scene/DiaryList/Controller/DiaryListViewController.swift
  Diary/Scene/DiaryRegistration/Controller/DiaryRegistrationViewController.swift
Labels: refactor, style
